import React, { useCallback, useEffect, useState } from 'react';
import { Image, RefreshControl, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { apiClient, BASE_URL } from '@/utils/api';
import { useThemeColors } from '@/context/ThemePreferencesContext';
import { Radius, Spacing, Typography } from '@/constants/theme';
import { ScreenShell } from '@/components/ui/ScreenShell';
import { Card } from '@/components/ui/Card';
import { SkeletonPage } from '@/components/ui/Skeleton';

type Data = { student: { name: string; fatherName: string | null; phone: string | null; emergencyContact: string | null; profilePictureUrl: string | null; loginRollNumber: string; classRollNumber: string; className: string; sectionName: string }; institution: { name: string; logoKey: string | null; signatureKey: string | null } };
const imageUrl = (value: string | null) => !value ? null : /^https?:\/\//i.test(value) ? value : `${BASE_URL}${value.startsWith('/') ? '' : '/'}${value}`;

export default function IdCardScreen() {
  const colors = useThemeColors();
  const [data, setData] = useState<Data | null>(null), [back, setBack] = useState(false), [loading, setLoading] = useState(true), [refreshing, setRefreshing] = useState(false), [error, setError] = useState('');
  const load = useCallback(async () => { try { setError(''); setData(await apiClient('/api/student/id-card')); } catch (err: unknown) { setError(err instanceof Error ? err.message : 'Could not load ID card.'); } finally { setLoading(false); setRefreshing(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  if (loading && !refreshing) return <SkeletonPage title="ID Card" subtitle="Loading your student identity." eyebrow="Student record" iconName="card-outline" variant="list" />;
  return <ScreenShell title="My ID Card" subtitle="Tap the card to view its other side." eyebrow="Student record" icon={<Ionicons name="card-outline" size={22} color="#FFF" />} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { setRefreshing(true); void load(); }} />}>
    {error || !data ? <Card><Text style={{ color: colors.error }}>{error || 'ID card is unavailable.'}</Text></Card> : <TouchableOpacity activeOpacity={0.92} onPress={() => setBack((value) => !value)}>
      {!back ? <View style={styles.front}>
        <View style={styles.brandRow}>{imageUrl(data.institution.logoKey) ? <Image source={{ uri: imageUrl(data.institution.logoKey)! }} style={styles.logo} /> : null}<Text numberOfLines={1} style={styles.institution}>{data.institution.name}</Text><Text style={styles.kind}>STUDENT ID</Text></View>
        <View style={styles.personRow}>{imageUrl(data.student.profilePictureUrl) ? <Image source={{ uri: imageUrl(data.student.profilePictureUrl)! }} style={styles.photo} /> : <View style={[styles.photo, styles.placeholder]}><Ionicons name="person-outline" size={36} color="rgba(255,255,255,.45)" /></View>}<View style={{ flex: 1 }}><Text style={styles.name}>{data.student.name}</Text>{data.student.fatherName ? <Text style={styles.father}>{data.student.fatherName}</Text> : null}<View style={styles.fields}><Field label="CLASS" value={data.student.className} /><Field label="SECTION" value={data.student.sectionName} /><Field label="ROLL NO." value={data.student.classRollNumber} /><Field label="UNIVERSAL ID" value={data.student.loginRollNumber.split('@')[0]} /></View></View></View>
      </View> : <View style={[styles.back, { borderColor: colors.border, backgroundColor: colors.surface }]}><View style={styles.backHead}><Text style={styles.backName}>{data.student.name}</Text><Text style={styles.gold}>{data.student.loginRollNumber.split('@')[0]}</Text></View><View style={styles.contacts}><Contact label="Student contact" value={data.student.phone || 'Not provided'} color={colors.text} muted={colors.textMuted} /><Contact label="Emergency contact" value={data.student.emergencyContact || 'Not provided'} color={colors.text} muted={colors.textMuted} /><Text style={[styles.verified, { color: colors.textMuted, borderTopColor: colors.border }]}>VERIFIED STUDENT · NISAAB360</Text></View></View>}
      <Text style={[styles.hint, { color: colors.textMuted }]}>{back ? 'Back' : 'Front'} · tap to flip</Text>
    </TouchableOpacity>}
  </ScreenShell>;
}

function Field({ label, value }: { label: string; value: string }) { return <View style={{ width: '48%' }}><Text style={styles.fieldLabel}>{label}</Text><Text numberOfLines={1} style={styles.fieldValue}>{value}</Text></View>; }
function Contact({ label, value, color, muted }: { label: string; value: string; color: string; muted: string }) { return <View><Text style={[styles.contactLabel, { color: muted }]}>{label}</Text><Text style={[styles.contactValue, { color }]}>{value}</Text></View>; }
const styles = StyleSheet.create({ front: { backgroundColor: '#0E1E3D', borderRadius: Radius.lg, overflow: 'hidden', minHeight: 238 }, brandRow: { flexDirection: 'row', alignItems: 'center', gap: 8, padding: 14, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: 'rgba(255,255,255,.12)' }, logo: { width: 25, height: 25, resizeMode: 'contain' }, institution: { flex: 1, color: '#F5F0E8', fontFamily: Typography.fontFamilyBold, fontSize: Typography.size.sm, textTransform: 'uppercase' }, kind: { color: '#D2B15C', fontFamily: Typography.fontFamilySemiBold, fontSize: 9, letterSpacing: 1 }, personRow: { flexDirection: 'row', gap: 15, padding: 18 }, photo: { width: 76, height: 94, borderRadius: Radius.md }, placeholder: { alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255,255,255,.08)', borderWidth: 1, borderColor: 'rgba(255,255,255,.14)' }, name: { color: '#FFF', fontFamily: Typography.fontFamilyBold, fontSize: Typography.size.lg }, father: { color: 'rgba(255,255,255,.5)', fontFamily: Typography.fontFamily, fontSize: Typography.size.xs, marginTop: 3 }, fields: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 16 }, fieldLabel: { color: 'rgba(255,255,255,.38)', fontSize: 8, letterSpacing: 1 }, fieldValue: { color: '#F5F0E8', fontFamily: Typography.fontFamilySemiBold, fontSize: Typography.size.sm, marginTop: 2 }, back: { borderWidth: 1, borderRadius: Radius.lg, minHeight: 238, overflow: 'hidden' }, backHead: { backgroundColor: '#0E1E3D', flexDirection: 'row', justifyContent: 'space-between', padding: 14 }, backName: { color: '#F5F0E8', fontFamily: Typography.fontFamilyBold, fontSize: Typography.size.sm, textTransform: 'uppercase' }, gold: { color: '#D2B15C', fontSize: Typography.size.xs }, contacts: { gap: 18, padding: Spacing.xl }, contactLabel: { textTransform: 'uppercase', letterSpacing: 1, fontSize: 9 }, contactValue: { fontFamily: Typography.fontFamilySemiBold, marginTop: 3 }, verified: { borderTopWidth: 1, paddingTop: 14, fontSize: 10, letterSpacing: 1 }, hint: { textAlign: 'center', marginTop: Spacing.sm, fontSize: Typography.size.xs } });
