import React, { useCallback, useEffect, useState } from 'react';
import { Alert, RefreshControl, StyleSheet, Text, TextInput, TouchableOpacity } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { apiClient } from '@/utils/api';
import { useThemeColors } from '@/context/ThemePreferencesContext';
import { Radius, Spacing, Typography } from '@/constants/theme';
import { ScreenShell } from '@/components/ui/ScreenShell';
import { Card } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { Modal } from '@/components/ui/Modal';
import { SkeletonList } from '@/components/ui/Skeleton';
import { EmptyState } from '@/components/ui/EmptyState';

type Ticket = { id: number; title: string; description: string; status: string; createdAt: string };
export default function TicketsScreen() {
  const colors = useThemeColors();
  const [tickets, setTickets] = useState<Ticket[]>([]), [nextCursor, setNextCursor] = useState<string | null>(null), [loading, setLoading] = useState(true), [refreshing, setRefreshing] = useState(false), [loadingMore, setLoadingMore] = useState(false), [showCreate, setShowCreate] = useState(false), [title, setTitle] = useState(''), [description, setDescription] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const load = useCallback(async (cursor?: string) => { try { setError(''); const suffix = cursor ? `?limit=25&cursor=${encodeURIComponent(cursor)}` : '?limit=25'; const data = await apiClient(`/api/tickets${suffix}`); setTickets((current) => cursor ? [...current, ...(data.tickets || [])] : data.tickets || []); setNextCursor(data.nextCursor || null); } catch (err: unknown) { setError(err instanceof Error ? err.message : 'Could not load support tickets.'); } finally { setLoading(false); setRefreshing(false); setLoadingMore(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function create() { if (!title.trim() || !description.trim()) return; setBusy(true); try { await apiClient('/api/tickets', { method: 'POST', body: JSON.stringify({ title: title.trim(), description: description.trim() }) }); setShowCreate(false); setTitle(''); setDescription(''); await load(); Alert.alert('Ticket created', 'Your institution can now review this request.'); } catch (err: unknown) { Alert.alert('Could not create ticket', err instanceof Error ? err.message : 'Please try again.'); } finally { setBusy(false); } }
  return <><ScreenShell title="Support Tickets" subtitle="Ask your institution for help and track the status." eyebrow="Support" icon={<Ionicons name="help-buoy-outline" size={22} color="#FFF" />} actions={<TouchableOpacity style={styles.add} onPress={() => setShowCreate(true)}><Ionicons name="add" size={23} color="#FFF" /></TouchableOpacity>} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { setRefreshing(true); void load(); }} />}>
    {loading && !refreshing ? <SkeletonList rows={4} /> : error && !tickets.length ? <Card><Text style={{ color: colors.error }}>{error}</Text></Card> : tickets.length === 0 ? <Card><EmptyState icon={<Ionicons name="chatbubbles-outline" size={25} color={colors.accent} />} title="No support requests" message="Need help from your institution? Create a request and track its progress here." action={<Button title="Create support request" onPress={() => setShowCreate(true)} />} /></Card> : tickets.map((ticket) => <Card key={ticket.id} title={ticket.title} headerRight={<Text style={[styles.status, { color: ticket.status === 'RESOLVED' ? colors.success : colors.warning }]}>{ticket.status}</Text>}><Text style={[styles.description, { color: colors.text }]}>{ticket.description}</Text><Text style={[styles.date, { color: colors.textMuted }]}>{new Date(ticket.createdAt).toLocaleString()}</Text></Card>)}
    {nextCursor ? <Button title={loadingMore ? 'Loading…' : 'Load older tickets'} variant="outline" loading={loadingMore} onPress={() => { setLoadingMore(true); void load(nextCursor); }} /> : null}
  </ScreenShell><Modal visible={showCreate} onClose={() => !busy && setShowCreate(false)} title="Create support ticket" footer={<><Button title="Cancel" variant="ghost" disabled={busy} onPress={() => setShowCreate(false)} /><Button title="Send ticket" loading={busy} disabled={!title.trim() || !description.trim()} onPress={() => void create()} /></>}><TextInput value={title} onChangeText={setTitle} maxLength={255} placeholder="Short title" placeholderTextColor={colors.textMuted} style={[styles.input, { color: colors.text, borderColor: colors.border }]} /><TextInput value={description} onChangeText={setDescription} multiline numberOfLines={5} placeholder="Explain what you need help with" placeholderTextColor={colors.textMuted} style={[styles.input, styles.textarea, { color: colors.text, borderColor: colors.border }]} /></Modal></>;
}
const styles = StyleSheet.create({ add: { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255,255,255,.16)' }, status: { fontFamily: Typography.fontFamilyBold, fontSize: Typography.size.xs }, description: { fontFamily: Typography.fontFamily, fontSize: Typography.size.sm, lineHeight: 20 }, date: { fontFamily: Typography.fontFamily, fontSize: Typography.size.xs, marginTop: Spacing.md }, input: { borderWidth: 1, borderRadius: Radius.md, padding: Spacing.md, fontFamily: Typography.fontFamily, marginBottom: Spacing.md }, textarea: { minHeight: 120, textAlignVertical: 'top' } });
