import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { Alert, RefreshControl, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { apiClient } from '@/utils/api';
import { useThemeColors } from '@/context/ThemePreferencesContext';
import { Radius, Spacing, Typography } from '@/constants/theme';
import { ScreenShell } from '@/components/ui/ScreenShell';
import { Card } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { SkeletonList } from '@/components/ui/Skeleton';

type Option = { id: number; name: string };
type History = { id: number; classId: number; subjectId: number | null; date: string; preview: string };
const today = () => new Date().toISOString().slice(0, 10);
export default function StaffDiaryScreen() {
  const colors = useThemeColors();
  const [classes, setClasses] = useState<Option[]>([]), [subjects, setSubjects] = useState<Option[]>([]), [classId, setClassId] = useState<number | null>(null), [subjectId, setSubjectId] = useState<number | null>(null), [date, setDate] = useState(today), [content, setContent] = useState(''), [history, setHistory] = useState<History[]>([]), [cursor, setCursor] = useState<string | null>(null), [loading, setLoading] = useState(true), [refreshing, setRefreshing] = useState(false), [saving, setSaving] = useState(false), [historyLoading, setHistoryLoading] = useState(false);
  const selected = useMemo(() => Boolean(classId && subjectId), [classId, subjectId]);
  const loadMeta = useCallback(async () => { try { const data = await apiClient('/api/staff/assignments?view=metadata'); const classMap = new Map<number, Option>(); (data.sectionOptions || []).forEach((item: any) => classMap.set(item.classId, { id: item.classId, name: item.className })); setClasses([...classMap.values()]); setSubjects(data.subjectOptions || []); } catch (err: unknown) { Alert.alert('Diary unavailable', err instanceof Error ? err.message : 'Could not load your assignments.'); } finally { setLoading(false); setRefreshing(false); } }, []);
  const loadEntry = useCallback(async () => { if (!classId || !subjectId) { setContent(''); return; } try { const data = await apiClient(`/api/staff/diary?view=entry&classId=${classId}&subjectId=${subjectId}&date=${date}`); setContent(data.diary?.content || ''); } catch (err: unknown) { Alert.alert('Could not load diary', err instanceof Error ? err.message : 'Please try again.'); } }, [classId, subjectId, date]);
  useEffect(() => { void loadMeta(); }, [loadMeta]); useEffect(() => { void loadEntry(); }, [loadEntry]);
  async function save() { if (!classId || !subjectId || !content.trim()) return; setSaving(true); try { await apiClient('/api/staff/diary', { method: 'POST', body: JSON.stringify({ classId, subjectId, date, content: content.trim() }) }); Alert.alert('Diary saved', 'Students can now see this entry.'); } catch (err: unknown) { Alert.alert('Could not save diary', err instanceof Error ? err.message : 'Please try again.'); } finally { setSaving(false); } }
  async function loadHistory(next?: string) { setHistoryLoading(true); try { const data = await apiClient(`/api/staff/diary?view=history&limit=20${next ? `&cursor=${encodeURIComponent(next)}` : ''}`); setHistory((current) => next ? [...current, ...(data.entries || [])] : data.entries || []); setCursor(data.nextCursor || null); } catch (err: unknown) { Alert.alert('Could not load history', err instanceof Error ? err.message : 'Please try again.'); } finally { setHistoryLoading(false); } }
  async function openHistoryEntry(entry: History) {
    setClassId(entry.classId); setDate(entry.date);
    if (entry.subjectId) { setSubjectId(entry.subjectId); return; }
    try { const data = await apiClient(`/api/staff/diary?view=entry&classId=${entry.classId}&date=${entry.date}`); Alert.alert(`General diary · ${entry.date}`, data.diary?.content || entry.preview); }
    catch (err: unknown) { Alert.alert('Could not open entry', err instanceof Error ? err.message : 'Please try again.'); }
  }
  return <ScreenShell title="Class Diary" subtitle="Publish homework and classwork to assigned students." eyebrow="Teaching" icon={<Ionicons name="book-outline" size={22} color="#FFF" />} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { setRefreshing(true); void loadMeta(); }} />}>
    {loading && !refreshing ? <SkeletonList rows={4} /> : <><Card title="Daily diary entry"><Text style={[styles.label, { color: colors.text }]}>Class</Text><View style={styles.options}>{classes.map((item) => <TouchableOpacity key={item.id} onPress={() => setClassId(item.id)} style={[styles.option, { borderColor: classId === item.id ? colors.accent : colors.border, backgroundColor: classId === item.id ? colors.primaryBg : colors.surface }]}><Text style={{ color: colors.text }}>{item.name}</Text></TouchableOpacity>)}</View><Text style={[styles.label, { color: colors.text }]}>Subject</Text><View style={styles.options}>{subjects.map((item) => <TouchableOpacity key={item.id} onPress={() => setSubjectId(item.id)} style={[styles.option, { borderColor: subjectId === item.id ? colors.accent : colors.border, backgroundColor: subjectId === item.id ? colors.primaryBg : colors.surface }]}><Text style={{ color: colors.text }}>{item.name}</Text></TouchableOpacity>)}</View><TextInput value={date} onChangeText={setDate} placeholder="YYYY-MM-DD" style={[styles.input, { color: colors.text, borderColor: colors.border }]} /><TextInput value={content} onChangeText={setContent} multiline numberOfLines={6} placeholder={selected ? 'Homework or classwork for today' : 'Select class and subject first'} placeholderTextColor={colors.textMuted} editable={selected} style={[styles.input, styles.textarea, { color: colors.text, borderColor: colors.border }]} /><Button title={saving ? 'Saving…' : 'Save diary entry'} loading={saving} disabled={!selected || !content.trim()} onPress={() => void save()} /></Card><Card title="Past entries" headerRight={<Button title={history.length ? 'Refresh' : 'Browse'} variant="outline" onPress={() => void loadHistory()} />}>{history.length === 0 && !historyLoading ? <Text style={[styles.empty, { color: colors.textMuted }]}>History loads only when requested.</Text> : history.map((entry) => <TouchableOpacity key={entry.id} style={[styles.history, { borderBottomColor: colors.border }]} onPress={() => void openHistoryEntry(entry)}><Text style={[styles.label, { color: colors.text }]}>{entry.date}{entry.subjectId === null ? ' · General entry' : ''}</Text><Text numberOfLines={3} style={[styles.preview, { color: colors.textMuted }]}>{entry.preview}</Text></TouchableOpacity>)}{cursor ? <Button title="Load older entries" variant="outline" loading={historyLoading} onPress={() => void loadHistory(cursor)} /> : null}</Card></>}
  </ScreenShell>;
}
const styles = StyleSheet.create({ label: { fontFamily: Typography.fontFamilySemiBold, fontSize: Typography.size.sm, marginBottom: Spacing.sm }, options: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.sm, marginBottom: Spacing.md }, option: { borderWidth: 1, borderRadius: Radius.full, paddingHorizontal: Spacing.md, paddingVertical: Spacing.sm }, input: { borderWidth: 1, borderRadius: Radius.md, padding: Spacing.md, marginBottom: Spacing.md, fontFamily: Typography.fontFamily }, textarea: { minHeight: 130, textAlignVertical: 'top' }, empty: { textAlign: 'center', paddingVertical: Spacing.lg }, history: { paddingVertical: Spacing.md, borderBottomWidth: StyleSheet.hairlineWidth }, preview: { fontFamily: Typography.fontFamily, fontSize: Typography.size.sm, lineHeight: 20 } });
